### ISSUE TITLE
FAQ page is missing some URLs

### ISSUE THREAD

**Issue by Noahkiq** [whats-this/landing#12]
The list of file hosting services on the FAQ page is missing some URLs (such as `light-theme-hurts.my-ey.es`)

**Comment by deansheather** [comment]
Will be fixed in #14. You can find a text file in the root of the repository too with a parseable list of domains in this PR.

Leaving this open until merge.

**Comment by martmists** [comment]
For the lib devs, what's a good way and/or interval to update this? I'd normally say on init, but for long running processes this won't work as well if it gets updated during runtime of the process.

**Comment by deansheather** [comment]
Probably could do it with a cron-job on a build server that will automatically fetch and apply every 30min or so if there are changes or something.

Libraries should leave the URL decisions up to the developer, though. I don't see any need to force developers to pick from a list if the list is constantly changing. The file is mostly meant for people who quickly need to see the list and application developers.

**Comment by deansheather** [comment]
#14 is closed, closing this issue.
